# CrimsonCFG-Name: Costumisation -> SSH Key
# CrimsonCFG-Description: Set's SSH keys
# CrimsonCFG-Essential: false
---
- name: SSH Key
  hosts: all
  become: true

  tasks:

      #######################
      # SSH Key
      #######################

    - name: Ensure .ssh directory exists
      ansible.builtin.file:
        path: "{{ user_home }}/.ssh"
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: '0700'
      changed_when: false

    - name: Set current date fact
      ansible.builtin.set_fact:
        today: "{{ lookup('pipe', 'date +%Y%m%d') }}"

    - name: Stat private key
      ansible.builtin.stat:
        path: "{{ user_home }}/.ssh/{{ ssh_private_key_name }}"
      register: priv_key_stat

    - name: Backup existing private key if present
      ansible.builtin.command:
        cmd: mv "{{ user_home }}/.ssh/{{ ssh_private_key_name }}" "{{ user_home }}/.ssh/{{ ssh_private_key_name }}_{{ today }}"
      args:
        removes: "{{ user_home }}/.ssh/{{ ssh_private_key_name }}"
      when:
        - ssh_private_key_name is defined
        - priv_key_stat.stat.exists

    - name: Stat public key
      ansible.builtin.stat:
        path: "{{ user_home }}/.ssh/{{ ssh_public_key_name }}"
      register: pub_key_stat

    - name: Backup existing public key if present
      ansible.builtin.command:
        cmd: mv "{{ user_home }}/.ssh/{{ ssh_public_key_name }}" "{{ user_home }}/.ssh/{{ ssh_public_key_name }}_{{ today }}"
      args:
        removes: "{{ user_home }}/.ssh/{{ ssh_public_key_name }}"
      when:
        - ssh_public_key_name is defined
        - pub_key_stat.stat.exists

    - name: Write SSH private key from variable
      ansible.builtin.copy:
        dest: "{{ user_home }}/.ssh/{{ ssh_private_key_name }}"
        content: "{{ ssh_private_key_content | default('') }}"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: '0600'
      when: ssh_private_key_content is defined and ssh_private_key_content | length > 0

    - name: Write SSH public key from variable
      ansible.builtin.copy:
        dest: "{{ user_home }}/.ssh/{{ ssh_public_key_name }}"
        content: "{{ ssh_public_key_content | default('') }}"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: '0644'
      when: ssh_public_key_content is defined and ssh_public_key_content | length > 0
