# CrimsonCFG-Name: Codium
# CrimsonCFG-Description: Install and setup Codium
# CrimsonCFG-Essential: false
---
- name: Install and setup Codium
  hosts: all
  become: true
  vars_files:
    - "{{ lookup('env', 'HOME') + '/.config/com.crimson.cfg/local.yml' }}"

  tasks:

    #######################
    # Install Codium
    #######################

    - name: Install VSCodium via Snap
      become: true
      community.general.snap:
        name: codium
        state: present
        classic: true

    #######################
    # Install ansible-lint
    #######################

    - name: Ensure ansible-lint is installed
      ansible.builtin.apt:
        name: ansible-lint
        state: present
        update_cache: true

    #######################
    # Install extensions
    #######################

    - name: Install VSCodium extensions
      become: true
      become_user: "{{ user }}"
      environment:
        HOME: "{{ user_home }}"
        PATH: "/snap/bin:{{ ansible_env.PATH }}"
      ansible.builtin.shell: |
        codium --install-extension {{ item }} --force
      loop:
        - redhat.ansible
        - redhat.vscode-xml
        - ms-azuretools.vscode-docker
        - yzhang.markdown-all-in-one
        - pkief.material-icon-theme
        - esbenp.prettier-vscode
        - ms-python.python
        - shd101wyy.markdown-preview-enhanced
        - eamodio.gitlens
        - github.vscode-pull-request-github
        - redhat.vscode-yaml
      register: codium_install
      failed_when: codium_install.rc != 0 and
                  '"already installed" not in codium_install.stderr'
