# CrimsonCFG-Name: Landscape Client
# CrimsonCFG-Description: Install Landscape Client
# CrimsonCFG-Essential: false
# CrimsonCFG-RequiredVars: false
---
- name: Install Landscape Client
  hosts: all
  become: true
  vars_files:
    - "{{ lookup('env', 'HOME') + '/.config/com.crimson.cfg/local.yml' }}"

  vars:
    account_name: "{{ landscape_account_name | default('standalone') }}"
    registration_key: "{{ landscape_registration_key | default('YOUR-REGISTRATION-KEY') }}"
    ping_url: "{{ landscape_ping_url | default('https://landscape.canonical.com/ping') }}"

  tasks:
    - name: Ensure snapd is installed
      apt:
        name: snapd
        state: present
        update_cache: yes

    - name: Install landscape client via snap
      snap:
        name: landscape-client
        state: present

    - name: Register machine with Landscape (snap)
      command: >
        landscape-client.config
        --computer-title "{{ ansible_hostname }}"
        --account-name "{{ account_name }}"
        --registration-key "{{ registration_key }}"
        --ping-url "{{ ping_url }}"
        --silent
      args:
        creates: /var/snap/landscape-client/common/etc/landscape-client.conf

    # The snap’s systemd unit:
    # snap.landscape-client.landscape-client.service
    - name: Ensure Landscape client service is enabled and running
      systemd:
        name: snap.landscape-client.landscape-client.service
        enabled: yes
        state: started

    - name: Show applied Landscape config
      command: cat /var/snap/landscape-client/common/etc/landscape-client.conf
      register: lc_conf
      changed_when: false

    - debug:
        var: lc_conf.stdout_lines

    # Wait until we see a successful contact/registration/exchange in logs
    - name: Wait for Landscape client to exchange/announce
      shell: |
        set -o pipefail
        journalctl -u snap.landscape-client.landscape-client.service -n 200 --no-pager \
          | grep -E "Registered|Registration complete|Starting urgent message exchange|Announced|exchange"
      register: lc_log_try
      changed_when: false
      failed_when: false
      retries: 12
      delay: 5
      until: lc_log_try.rc == 0

    - name: Show last Landscape client log lines
      shell: journalctl -u snap.landscape-client.landscape-client.service -n 80 --no-pager
      register: lc_logs
      changed_when: false

    - debug:
        var: lc_logs.stdout_lines

    - name: Assert registration/exchange occurred
      assert:
        that:
          - lc_log_try.rc == 0
        fail_msg: >
          No registration/exchange markers found in logs. Check registration key, account name,
          network access to {{ ping_url }}, or try re-registering.
        success_msg: Landscape client contacted the server successfully.
