# CrimsonCFG-Name: Landscape Client
# CrimsonCFG-Description: Install Landscape Client
# CrimsonCFG-Essential: false
# CrimsonCFG-RequiredVars: false
---
- name: Install Landscape Client
  hosts: all
  become: true
  vars_files:
    - "{{ lookup('env', 'HOME') + '/.config/com.crimson.cfg/local.yml' }}"

  vars:
    account_name: "{{ landscape_account_name | default('standalone') }}"
    registration_key: "{{ landscape_registration_key | default('YOUR-REGISTRATION-KEY') }}"
    ping_url: "{{ landscape_ping_url | default('https://landscape.canonical.com/ping') }}"

  tasks:
    - name: Ensure snapd is installed
      apt:
        name: snapd
        state: present
        update_cache: yes

    - name: Install landscape client via snap
      snap:
        name: landscape-client
        state: present

    - name: Register machine with Landscape (snap, idempotent)
      command: >
        landscape-client.config
        --computer-title "{{ ansible_hostname }}"
        --account-name "{{ account_name }}"
        --registration-key "{{ registration_key }}"
        --ping-url "{{ ping_url }}"
        --silent
      args:
        # Snap stores its config under /var/snap/...
        creates: /var/snap/landscape-client/common/etc/landscape-client.conf

    - name: Ensure Landscape client service is enabled and running
      systemd:
        name: snap.landscape-client.landscape-client.service
        enabled: yes
        state: started

    # ---------- Debug / verification via systemctl & journalctl ----------

    - name: Show Landscape client service status (systemctl)
      command: systemctl status snap.landscape-client.landscape-client.service --no-pager
      register: lc_status
      changed_when: false

    - name: Debug service status
      debug:
        var: lc_status.stdout_lines

    - name: Tail last 200 journal lines for Landscape client
      command: journalctl -u snap.landscape-client.landscape-client.service -n 200 --no-pager
      register: lc_journal
      changed_when: false
      failed_when: false

    - name: Debug journal tail
      debug:
        var: lc_journal.stdout_lines

    - name: Show applied Landscape snap config
      command: cat /var/snap/landscape-client/common/etc/landscape-client.conf
      register: lc_conf
      changed_when: false
      failed_when: false

    - name: Debug Landscape config
      debug:
        var: lc_conf.stdout_lines
