# CrimsonCFG-Name: Prism Launcher
# CrimsonCFG-Description: Install Prism Launcher (Minecraft Launcher)
# CrimsonCFG-Essential: false
# CrimsonCFG-RequiredVars: false
---
- name: Install Prism Launcher (Minecraft Launcher)
  hosts: all
  become: true
  vars_files:
    - "{{ lookup('env', 'HOME') + '/.config/com.crimson.cfg/local.yml' }}"
  
  # Prism-Launcher-specific variables moved from local.yml to playbook
  vars:
    prism_appimage_dir: '{{ appimg_directory }}/PrismLauncher'
    prism_appimage_filename: PrismLauncher.AppImage
    prism_appimage_url: https://github.com/PrismLauncher/PrismLauncher/releases/latest/download/PrismLauncher-Linux-{{ ansible_architecture }}.AppImage

  tasks:

    #######################
    # Ensure AppImage folder exists
    #######################
    - name: Create AppImage folder for PrismLauncher
      ansible.builtin.file:
        path: "{{ prism_appimage_dir }}"
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: '0755'

    #######################
    # Download AppImage
    #######################
    - name: Download Prism Launcher AppImage
      ansible.builtin.get_url:
        url: "{{ prism_appimage_url }}"
        dest: "{{ prism_appimage_dir }}/{{ prism_appimage_filename }}"
        mode: '0755'
        owner: "{{ user }}"
        group: "{{ user }}"

    #######################
    # Extract icon from AppImage
    #######################
    - name: Extract AppImage to get icon
      ansible.builtin.shell: |
        cd {{ prism_appimage_dir }}
        ./{{ prism_appimage_filename }} --appimage-extract
      args:
        executable: /bin/bash
      changed_when: false

    - name: Check if Prism Launcher icon exists
      ansible.builtin.stat:
        path: "{{ prism_appimage_dir }}/squashfs-root/usr/share/icons/hicolor/scalable/apps/org.prismlauncher.PrismLauncher.svg"
      register: prism_icon_stat

    - name: Copy icon to proper location
      ansible.builtin.copy:
        src: "{{ prism_appimage_dir }}/squashfs-root/usr/share/icons/hicolor/scalable/apps/org.prismlauncher.PrismLauncher.svg"
        dest: "{{ prism_appimage_dir }}/PrismLauncher.svg"
        remote_src: true
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: '0644'
      when: prism_icon_stat.stat.exists

    - name: Clean up extracted AppImage
      ansible.builtin.file:
        path: "{{ prism_appimage_dir }}/squashfs-root"
        state: absent

    #######################
    # Create .desktop file for Prism Launcher
    #######################
    - name: Create Prism Launcher .desktop entry in user applications
      ansible.builtin.copy:
        dest: "{{ desktop_dotfile_folder }}/PrismLauncher.desktop"
        content: |
          [Desktop Entry]
          Name=Prism Launcher
          Comment=Minecraft launcher with support for multiple instances
          GenericName=Minecraft Launcher
          Exec={{ prism_appimage_dir }}/{{ prism_appimage_filename }} %F
          Icon={{ prism_appimage_dir }}/PrismLauncher.svg
          Type=Application
          StartupNotify=false
          StartupWMClass=PrismLauncher
          Categories=Game;Minecraft;
          MimeType=application/x-prismlauncher-instance;
          Actions=new-instance;

          [Desktop Action new-instance]
          Name=New Instance
          Exec={{ prism_appimage_dir }}/{{ prism_appimage_filename }} --new-instance
          Icon={{ prism_appimage_dir }}/PrismLauncher.svg
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: '0644'
