# CrimsonCFG-Name: Syncthing
# CrimsonCFG-Description: Install Syncthing
# CrimsonCFG-Essential: false
# CrimsonCFG-RequiredVars: false
---
- name: Install Syncthing
  hosts: all
  become: true
  vars_files:
    - "{{ lookup('env', 'HOME') + '/.config/com.crimson.cfg/local.yml' }}"

  tasks:
      - name: Update apt cache
        ansible.builtin.apt:
        update_cache: true

      - name: Install packages
        sansible.builtin.apt:
          name:
            - syncthing
            - syncthingtray
          state: present
          update_cache: yes

      - name: Ensure autostart directory exists
        ansible.builtin.file:
          path: "{{ user_home }}/.config/autostart"
          state: directory
          owner: "{{ user }}"
          group: "{{ user }}"
          mode: "0755"

      - name: Add Syncthing Tray to autostart (render from template)
        ansible.builtin.template:
          src: "{{ playbook_dir }}/../templates/syncthing.desktop.j2"
          dest: "{{ user_home }}/.config/autostart/syncthingtray.desktop"
          owner: "{{ user }}"
          group: "{{ user }}"
          mode: "0644"
        tags: syncthing
