# CrimsonCFG-Name: Syncthing
# CrimsonCFG-Description: Install Syncthing
# CrimsonCFG-Essential: false
# CrimsonCFG-RequiredVars: false
---
- name: Install Syncthing and tray
  hosts: all
  become: true
  vars_files:
    - "{{ lookup('env', 'HOME') + '/.config/com.crimson.cfg/local.yml' }}"

  tasks:
    - name: Install packages
      ansible.builtin.apt:
        name:
          - syncthing
          - syncthingtray
        state: present
        update_cache: true

    - name: Ensure autostart directory exists
      ansible.builtin.file:
        path: "{{ user_home }}/.config/autostart"
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: "0755"

    - name: Add Syncthing Tray to autostart
      ansible.builtin.template:
        src: syncthing.desktop.j2
        dest: "{{ user_home }}/.config/autostart/syncthingtray.desktop"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: "0644"
      tags: syncthing
