# CrimsonCFG-Name: Tailscale
# CrimsonCFG-Description: Install Tailscale VPN client
# CrimsonCFG-Essential: false
---
- name: Install Tailscale
  hosts: all
  become: true
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install required packages for Tailscale
      ansible.builtin.apt:
        name:
          - curl
          - apt-transport-https
        state: present

    - name: Add Tailscale GPG key
      ansible.builtin.shell: |
        curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/noble.noarmor.gpg | sudo tee /usr/share/keyrings/tailscale-archive-keyring.gpg >/dev/null
      args:
        creates: /usr/share/keyrings/tailscale-archive-keyring.gpg

    - name: Add Tailscale repository
      ansible.builtin.shell: |
        curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/noble.tailscale-keyring.list | sudo tee /etc/apt/sources.list.d/tailscale.list
      args:
        creates: /etc/apt/sources.list.d/tailscale.list

    - name: Update apt cache after adding repository
      ansible.builtin.apt:
        update_cache: true

    - name: Install Tailscale
      ansible.builtin.apt:
        name: tailscale
        state: present

    - name: Enable and start Tailscale service
      ansible.builtin.systemd:
        name: tailscaled
        enabled: true
        state: started
