# CrimsonCFG-Name: Tailscale
# CrimsonCFG-Description: Install Tailscale VPN client
# CrimsonCFG-Essential: false
---
- name: Install Tailscale
  hosts: all
  become: true
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install required packages for Tailscale
      ansible.builtin.apt:
        name:
          - curl
          - apt-transport-https
        state: present

    - name: Download Tailscale GPG key
      ansible.builtin.get_url:
        url: https://pkgs.tailscale.com/stable/ubuntu/jammy.noarmor.gpg
        dest: /usr/share/keyrings/tailscale-archive-keyring.gpg
        mode: '0644'

    - name: Add Tailscale repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/tailscale-archive-keyring.gpg] https://pkgs.tailscale.com/stable/ubuntu jammy main"
        state: present
        filename: tailscale

    - name: Update apt cache after adding repository
      ansible.builtin.apt:
        update_cache: true

    - name: Install Tailscale
      ansible.builtin.apt:
        name: tailscale
        state: present

    - name: Enable and start Tailscale service
      ansible.builtin.systemd:
        name: tailscaled
        enabled: true
        state: started
