# CrimsonCFG-Name: Virtualisation
# CrimsonCFG-Description: Install GNOME Boxes, QEMU/KVM, and Virt-Manager
# CrimsonCFG-Essential: false
---
- name: Install GNOME Boxes and QEMU/KVM and configure user permissions
  hosts: all
  vars_files:
    - "{{ lookup('env', 'HOME') + '/.config/com.crimson.cfg/local.yml' }}"


  tasks:

    - name: Install GNOME Boxes, QEMU/KVM, and Virt-Manager
      become: true
      ansible.builtin.apt:
        name:
          - gnome-boxes
          - qemu-kvm
          - qemu-utils
          - libvirt-daemon-system
          - libvirt-clients
          - bridge-utils
          - virt-manager
        state: present

    - name: Ensure user is in libvirt group
      become: true
      ansible.builtin.user:
        name: "{{ user }}"
        groups: libvirt
        append: true

    - name: Ensure user is in kvm group
      become: true
      ansible.builtin.user:
        name: "{{ user }}"
        groups: kvm
        append: true

    - name: Ensure user has a libvirt config directory
      become: false
      ansible.builtin.file:
        path: "/home/{{ user }}/.config/libvirt"
        state: directory
        mode: '0755'
        owner: "{{ user }}"
        group: "{{ user }}"

    - name: Enable and start libvirtd service
      become: true
      ansible.builtin.systemd:
        name: libvirtd
        enabled: true
        state: started

    - name: Verify libvirt socket access without sudo
      become: false
      ansible.builtin.command: "virsh list --all"
      register: virsh_output
      ignore_errors: true
      changed_when: false

    - name: Show test output
      become: false
      ansible.builtin.debug:
        var: virsh_output.stdout

    ## ----------------------------------------------------
    ## Pin App to GNOME dock
    ## ----------------------------------------------------
    - name: Ensure python3-psutil is installed for dconf module
      ansible.builtin.apt:
        name: python3-psutil
        state: present

    - name: Get current GNOME dock favorites
      community.general.dconf:
        key: /org/gnome/shell/favorite-apps
        state: read
      become: true
      become_user: "{{ user }}"
      environment:
        HOME: "{{ user_home }}"
      register: current_favorites

    - name: Normalize GNOME favorites value to a list
      ansible.builtin.set_fact:
        gnome_favorites_list: >-
          {{
            (current_favorites.value
              | default([])
              | from_yaml
              if (current_favorites.value is string)
              else (current_favorites.value | default([]) | list)
            )
          }}

    - name: Pin app to GNOME dock favorites
      community.general.dconf:
        key: /org/gnome/shell/favorite-apps
        value: >-
          {{
            (gnome_favorites_list +
              ([app_desktop_file] if app_desktop_file not in gnome_favorites_list else [])
            ) | to_json
          }}
        state: present
      become: true
      become_user: "{{ user }}"
      environment:
        HOME: "{{ user_home }}"
      vars:
        app_desktop_file: "gnome-boxes.desktop"
      when: app_desktop_file not in gnome_favorites_list
